# Generated by Django 3.1.3 on 2020-11-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
