# Generated by Django 3.1.3 on 2020-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_auto_20201116_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
