# Generated by Django 3.1.3 on 2020-11-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0004_auto_20201116_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(default='None'),
        ),
    ]
